function [mc,mean_abs_corr,per_neg_corr,per_pos_corr] = ...
    stats_sectors(C_hat,sec_eig,n_secs,freq_bin,pos_thresh,neg_thresh)

% Code to compute statistics of the RoCA sectors
% 
% Last updated: 2017-03-25
% 
% INPUT
%     C_hat                 M-by-M sized cleaned correlation matrix
%     sec_eig               1-by-(alpha) cell consisting of sectors formed
%                           using the RoCA method (indices according to
%                           M sites)
%     n_secs                Number of RoCA sectors
%     freq_bin              1-by-M vector consisting of frequency of
%                           dominant amino acid at each site
%     pos_thresh            threshold defining significnat positive
%                           correlations
%     neg_thresh            threshold defining significnat negative
%                           correlations
%     
% OUTPUT
%     mc                    1-by-(n_secs) vector consisting of mean
%                           conservation of sites in each sector
%     mean_abs_corr         1-by-(n_secs) vector consisting of mean
%                           absolute correlation of sites in each sector
%     per_neg_corr          1-by-(n_secs) vector consisting of percentage
%                           of negatively correlated sites in each sector
%     per_pos_corr          1-by-(n_secs) vector consisting of percentage
%                           of positively correlated sites in each sector

%% Defining color for the bar plot

color_darkgrey = 115*ones(1,3)/255;

%% Calculating the statistics

mc = zeros(1,n_secs);
mean_abs_corr = zeros(1,n_secs);
per_neg_corr = zeros(1,n_secs);
per_pos_corr = zeros(1,n_secs);

for kk = 1:n_secs
    mc(kk) = mean(freq_bin(sec_eig{kk}));
    mean_abs_corr(kk) = mean(abs(obtain_vec_triu_matrix(C_hat(sec_eig{kk},sec_eig{kk}))));
    [~,per_neg_corr(kk)] = neg_corr_calc(sec_eig{kk},C_hat,neg_thresh);
    [~,per_pos_corr(kk)] = pos_corr_calc(sec_eig{kk},C_hat,pos_thresh);
end

%% Mean conservation and mean absolute correlation


figure('name','Statistics of RoCA sectors','units','normalized','outerposition',[0 0 1 1])
subplot(2,2,1)
bar(1:n_secs,mc,0.3,'FaceColor',color_darkgrey,'EdgeColor','k')
ylabel('Mean conservation')
% xlabel('Sector number')
axis([0.5 n_secs+0.5 min(mc)-0.1 1])
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'on'      , ...
  'XGrid'       , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.1 .1 .1], ...
  'YColor'      , [.1 .1 .1], ...
  'YTick'       , 0:0.1:1, ...
  'LineWidth'   , 1        );

%
subplot(2,2,2)
bar(1:n_secs,mean_abs_corr,0.3,'FaceColor',color_darkgrey,'EdgeColor','k')
ylabel('Mean absolute correlation')
% xlabel('Sector number')
axis([0.5 n_secs+0.5 0 max(mean_abs_corr)+0.05])
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'on'      , ...
  'XGrid'       , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.1 .1 .1], ...
  'YColor'      , [.1 .1 .1], ...
  'YTick'       , 0:0.05:1, ...
  'LineWidth'   , 1        );



%% Negative and positive correlations

subplot(2,2,3)
bar(1:n_secs,per_neg_corr,0.3,'FaceColor',color_darkgrey,'EdgeColor','k')
ylabel('%Negative correlations')
xlabel('Sector number')
xlim([0.5 n_secs+0.5])
ylim([0 min(max(per_neg_corr)+5,100)])
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'on'      , ...
  'XGrid'       , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.1 .1 .1], ...
  'YColor'      , [.1 .1 .1], ...
  'YTick'       , 0:5:100, ...
  'LineWidth'   , 1        );

subplot(2,2,4)
bar(1:n_secs,per_pos_corr,0.3,'FaceColor',color_darkgrey,'EdgeColor','k')
ylabel('%Positive correlations')
xlabel('Sector number')
xlim([0.5 n_secs+0.5])
ylim([0 max(max(per_pos_corr)+5,100)])
% grid on
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'on'      , ...
  'XGrid'       , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.1 .1 .1], ...
  'YColor'      , [.1 .1 .1], ...
  'YTick'       , 0:20:100, ...
  'LineWidth'   , 1        );


